[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
ignore = "E203, E266, E501, W503"
select = "B,C,E,F,W,T4,B9"
