# Generated by Django 4.2.26 on 2026-01-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='academic_period_system',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='current_term',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='has_three_terms',
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='current_academic_year',
            field=models.ForeignKey(blank=True, help_text='Link to the active academic year in the standalone system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_configurations', to='core.academicyear', verbose_name='Current Academic Year'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='default_academic_period_system',
            field=models.CharField(choices=[('TERM', 'Term System (3 terms)'), ('SEMESTER', 'Semester System (2 semesters)'), ('QUARTER', 'Quarter System (4 quarters)'), ('TRIMESTER', 'Trimester System (3 trimesters)')], default='TERM', help_text='Default system used for academic periods (Terms, Semesters, etc.)', max_length=10, verbose_name='Default Academic Period System'),
        ),
    ]
