# Generated by Django 4.2.11 on 2025-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(choices=[('ADMISSION', 'Admission Fees'), ('TUITION', 'Tuition Fees'), ('FEEDING', 'Feeding Fees'), ('UNIFORM', 'Uniform Fees'), ('BOOKS', 'Books and Materials'), ('TRANSPORT', 'Transportation Fees'), ('OTHER', 'Other Fees')], max_length=100),
        ),
    ]
