# Generated by Django 4.2.7 on 2025-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('ADMISSION', 'Admission Fees'), ('TRANSPORT', 'Transport Fees'), ('TECHNOLOGY', 'Technology Fee'), ('EXAMINATION', 'Examination Fees'), ('UNIFORM', 'Uniform Fees'), ('PTA', 'PTA Fees'), ('EXTRA_CLASSES', 'Extra Classes Fees')], max_length=100),
        ),
    ]
