# Generated by Django 4.2.11 on 2025-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
