# Generated by Django 4.2.26 on 2025-12-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parentguardian_account_created_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['class_level', 'subject', 'academic_year'], name='core_classa_class_l_59935a_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['teacher', 'is_active'], name='core_classa_teacher_8aefd4_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['is_active', 'academic_year'], name='core_classa_is_acti_867ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['class_level', 'is_active'], name='core_classa_class_l_1b666d_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject', 'academic_year', 'term'], name='core_grade_student_60c99b_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['total_score', 'ges_grade'], name='core_grade_total_s_bbb949_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['created_at'], name='core_grade_created_1a1fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['class_assignment', 'academic_year', 'term'], name='core_grade_class_a_e5a634_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'class_assignment'], name='core_grade_student_f03bed_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['academic_year', 'term', 'class_level'], name='core_grade_academi_f31478_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='core_studen_student_fa4380_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_level', 'is_active'], name='core_studen_class_l_cb837a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='core_studen_last_na_d07597_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active', 'class_level'], name='core_studen_is_acti_8f110e_idx'),
        ),
    ]
