# Generated by Django 4.2.7 on 2025-11-22 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_feecategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkFeeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Bulk Create'), ('update', 'Bulk Update'), ('status_update', 'Status Update'), ('amount_adjustment', 'Amount Adjustment'), ('due_date_update', 'Due Date Update')], max_length=20)),
                ('description', models.TextField()),
                ('total_affected', models.PositiveIntegerField(default=0)),
                ('successful_operations', models.PositiveIntegerField(default=0)),
                ('failed_operations', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Fee Operation',
                'verbose_name_plural': 'Bulk Fee Operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkFeeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('successful_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('errors', models.JSONField(blank=True, default=dict, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Fee Import',
                'verbose_name_plural': 'Bulk Fee Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
