# Generated by Django 4.2.11 on 2025-08-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fee_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'student__last_name'], 'verbose_name': 'Student Attendance', 'verbose_name_plural': 'Student Attendances'},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date', 'period')},
        ),
    ]
