# Generated by Django 4.2.26 on 2025-12-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classassignment_core_classa_class_l_59935a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['period_number'], 'permissions': [('can_view_timeslot', 'Can view time slot'), ('manage_timeslot', 'Can manage time slot')], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['class_level', 'day_of_week'], 'permissions': [('can_view_timetable', 'Can view timetable'), ('manage_timetable', 'Can manage timetable')], 'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetables'},
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['time_slot__period_number'], 'permissions': [('view_timetable_entry', 'Can view timetable entry'), ('manage_timetable_entry', 'Can manage timetable entry')], 'verbose_name': 'Timetable Entry', 'verbose_name_plural': 'Timetable Entries'},
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='break_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
