# Generated by Django 4.2.26 on 2025-12-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timeslot_options_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
