# Generated by Django 4.2.11 on 2025-08-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentattendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_fees_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_rate', models.FloatField()),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AttendanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('P1', 'Primary 1'), ('P2', 'Primary 2'), ('P3', 'Primary 3'), ('P4', 'Primary 4'), ('P5', 'Primary 5'), ('P6', 'Primary 6'), ('J1', 'JHS 1'), ('J2', 'JHS 2'), ('J3', 'JHS 3')], max_length=20)),
                ('date', models.DateField()),
                ('present_count', models.IntegerField()),
                ('absent_count', models.IntegerField()),
                ('late_count', models.IntegerField()),
                ('attendance_rate', models.FloatField()),
            ],
            options={
                'unique_together': {('class_level', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GradeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('P1', 'Primary 1'), ('P2', 'Primary 2'), ('P3', 'Primary 3'), ('P4', 'Primary 4'), ('P5', 'Primary 5'), ('P6', 'Primary 6'), ('J1', 'JHS 1'), ('J2', 'JHS 2'), ('J3', 'JHS 3')], max_length=20)),
                ('average_score', models.FloatField()),
                ('highest_score', models.FloatField()),
                ('lowest_score', models.FloatField()),
                ('date_calculated', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('class_level', 'subject', 'date_calculated')},
            },
        ),
    ]
