# Generated by Django 4.2.26 on 2025-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timeslot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='feedback_document',
            field=models.FileField(blank=True, null=True, upload_to='assignment_feedback/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='graded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True, help_text='Detailed assignment instructions'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='What students will learn'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='resources',
            field=models.TextField(blank=True, help_text='Recommended resources/links'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.FileField(blank=True, null=True, upload_to='assignment_rubrics/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sample_solution',
            field=models.FileField(blank=True, null=True, upload_to='sample_solutions/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_comments',
            field=models.TextField(blank=True),
        ),
    ]
