# Generated by Django 4.2.11 on 2025-08-11 23:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_analyticscache_financialanalytics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-date_recorded'], 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.RemoveIndex(
            model_name='fee',
            name='core_fee_receipt_2ed792_idx',
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='core.feecategory'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Part Payment'), ('overdue', 'Overdue')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='recorded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='core.student'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['student'], name='core_fee_student_e40f98_idx'),
        ),
    ]
