# Generated by Django 4.2.26 on 2025-12-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_feedback_document_assignment_graded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='feedback_document',
            field=models.FileField(blank=True, null=True, upload_to='assignment_feedback/'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='graded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Flag for draft submissions'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='last_viewed_by_student',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='last_viewed_by_teacher',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='rubric_score',
            field=models.JSONField(blank=True, help_text='JSON structure for rubric-based scoring', null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='teacher_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['graded_date'], name='core_studen_graded__6ad214_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['score'], name='core_studen_score_674ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['student', 'status'], name='core_studen_student_a63d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['assignment', 'status'], name='core_studen_assignm_cac8de_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['created_at'], name='core_studen_created_aadb24_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['updated_at'], name='core_studen_updated_ab1315_idx'),
        ),
    ]
