# Generated by Django 4.2.11 on 2025-08-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fee_options_alter_feepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
