# Generated by Django 4.2.26 on 2025-12-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentassignment_feedback_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submissions',
            field=models.BooleanField(default=False, help_text='Allow students to submit after the due date'),
        ),
    ]
