# Generated by Django 4.2.26 on 2025-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assignment_allow_late_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='feedback_document',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='graded_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher_comments',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Assignment document/attachment', null=True, upload_to='assignment_attachments/'),
        ),
    ]
