# Generated by Django 4.2.26 on 2025-12-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_assignment_feedback_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('online', 'Online Payment'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Part Payment'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('ADMISSION', 'Admission Fees'), ('TRANSPORT', 'Transport Fees'), ('TECHNOLOGY', 'Technology Fee'), ('EXAMINATION', 'Examination Fees'), ('UNIFORM', 'Uniform Fees'), ('PTA', 'PTA Fees'), ('EXTRA_CLASSES', 'Extra Classes Fees'), ('LIBRARY', 'Library Fees'), ('SPORTS', 'Sports Fees'), ('MEDICAL', 'Medical Fees'), ('DEVELOPMENT', 'Development Levy'), ('OTHER', 'Other Fees')], max_length=100),
        ),
    ]
