# Generated by Django 4.2.11 on 2025-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
