# Generated by Django 4.2.26 on 2025-12-20 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_remove_parentmessage_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['-academic_year', '-term', 'student__last_name'], 'verbose_name': 'Report Card', 'verbose_name_plural': 'Report Cards'},
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='academic_year',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', 'Format: YYYY/YYYY')]),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average score across all subjects', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='overall_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (90-100)'), ('A', 'A (80-89)'), ('B+', 'B+ (70-79)'), ('B', 'B (60-69)'), ('C+', 'C+ (50-59)'), ('C', 'C (40-49)'), ('D+', 'D+ (30-39)'), ('D', 'D (20-29)'), ('E', 'E (0-19)')], help_text='Overall grade based on average score', max_length=2),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='principal_remarks',
            field=models.TextField(blank=True, help_text='Comments from principal'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.student'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='teacher_remarks',
            field=models.TextField(blank=True, help_text='Comments from class teacher'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='core_report_student_28f0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['is_published'], name='core_report_is_publ_4c4a66_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['average_score'], name='core_report_average_a1db18_idx'),
        ),
    ]
