# Generated by Django 4.2.11 on 2025-08-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_auditlog_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_model_n_3fb686_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_action_096de0_idx',
        ),
    ]
