# Generated by Django 4.2.11 on 2025-08-16 23:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_system', models.CharField(choices=[('GES', 'Ghana Education System (Primary/JHS)'), ('WASSCE', 'West African Senior School Certificate Exam')], default='GES', max_length=10)),
                ('is_locked', models.BooleanField(default=False, help_text='Lock the grading system to prevent changes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['academic_year', 'term', 'student__last_name']},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='ges_grade',
            field=models.CharField(choices=[('1', '1 (90-100%) - Outstanding'), ('2', '2 (80-89%) - Excellent'), ('3', '3 (70-79%) - Very Good'), ('4', '4 (60-69%) - Good'), ('5', '5 (50-59%) - Satisfactory'), ('6', '6 (40-49%) - Fair'), ('7', '7 (30-39%) - Weak'), ('8', '8 (20-29%) - Very Weak'), ('9', '9 (0-19%) - Fail'), ('N/A', 'Not Available')], default='N/A', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='class_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classassignment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classwork_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Classwork (30%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Exam (50%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='homework_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Homework (10%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Test (10%)'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'academic_year', 'term')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
    ]
