# Generated by Django 4.2.26 on 2025-12-20 23:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_reportcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='classwork_weight',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Percentage weight for classwork assessments', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Classwork Weight (%)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='exam_weight',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage weight for final examinations', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Exam Weight (%)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_1_min',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Minimum percentage for Grade 1 (Excellent)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 1 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_2_min',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Minimum percentage for Grade 2 (Very Good)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 2 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_3_min',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum percentage for Grade 3 (Good)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 3 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_4_min',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum percentage for Grade 4 (Credit)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 4 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_5_min',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum percentage for Grade 5 (Credit)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 5 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_6_min',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Minimum percentage for Grade 6 (Pass)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 6 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_7_min',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Minimum percentage for Grade 7 (Pass)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 7 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_8_min',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Minimum percentage for Grade 8 (Weak)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 8 Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='grade_9_max',
            field=models.DecimalField(decimal_places=2, default=19.99, help_text='Maximum percentage for Grade 9 (Very Weak/Fail)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Grade 9 Maximum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='has_three_terms',
            field=models.BooleanField(default=True, help_text='School operates on 3-term system', verbose_name='Three-Term System'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='homework_weight',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage weight for homework assignments', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Homework Weight (%)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_a_min',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Minimum percentage for A', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='A Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_a_plus_min',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Minimum percentage for A+', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='A+ Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_b_min',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum percentage for B', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='B Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_b_plus_min',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum percentage for B+', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='B+ Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_c_min',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Minimum percentage for C', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='C Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_c_plus_min',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum percentage for C+', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='C+ Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_d_min',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Minimum percentage for D', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='D Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_d_plus_min',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Minimum percentage for D+', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='D+ Minimum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='letter_f_max',
            field=models.DecimalField(decimal_places=2, default=19.99, help_text='Maximum percentage for F (Fail)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='F Maximum'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='passing_mark',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Minimum percentage required to pass', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Passing Mark (%)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='school_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary School (P1-P6)'), ('JHS', 'Junior High School (JHS1-JHS3)'), ('COMBINED', 'Combined Primary and JHS'), ('SHS', 'Senior High School'), ('OTHER', 'Other')], default='COMBINED', help_text='Select the school level', max_length=20, verbose_name='School Level'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='test_weight',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage weight for tests', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Test Weight (%)'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='allow_staff_access',
            field=models.BooleanField(default=True, help_text='Allow all staff users to access the system during maintenance', verbose_name='Allow Staff Access'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='allow_superuser_access',
            field=models.BooleanField(default=True, help_text='Allow all superusers to access the system during maintenance', verbose_name='Allow Superuser Access'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Comma-separated list of IPs allowed during maintenance', verbose_name='Allowed IPs'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the system during maintenance', related_name='maintenance_bypass_users', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Maintenance Active'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='message',
            field=models.TextField(blank=True, help_text='Message to display to users during maintenance', verbose_name='Maintenance Message'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency Maintenance'), ('SCHEDULED', 'Scheduled Maintenance'), ('UPGRADE', 'System Upgrade'), ('BACKUP', 'System Backup')], default='SCHEDULED', max_length=20, verbose_name='Maintenance Type'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='message',
            field=models.TextField(help_text='Message to display to users during maintenance', verbose_name='User Message'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Maintenance Title'),
        ),
        migrations.AlterField(
            model_name='scheduledmaintenance',
            name='was_executed',
            field=models.BooleanField(default=False, verbose_name='Was Executed'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', 'Academic year must be in format YYYY/YYYY')], verbose_name='Current Academic Year'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='current_term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], default=1, verbose_name='Current Term'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='grading_system',
            field=models.CharField(choices=[('GES', 'Ghana Education System (1-9)'), ('LETTER', 'Letter Grading System (A-F)'), ('BOTH', 'Both Systems'), ('CUSTOM', 'Custom Grading System')], default='GES', help_text='Select the grading system to use', max_length=10, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock the configuration to prevent changes', verbose_name='Configuration Locked'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Principal's Name"),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='school_address',
            field=models.TextField(default='', verbose_name='School Address'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='School Email'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='school_name',
            field=models.CharField(default='Ghana Education Service School', max_length=200, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='school_phone',
            field=models.CharField(blank=True, help_text='10-digit phone number starting with 0 (e.g., 0245478847)', max_length=10, validators=[django.core.validators.RegexValidator('^0\\d{9}$', message='Phone number must be 10 digits starting with 0 (e.g., 0245478847)')], verbose_name='School Phone'),
        ),
        migrations.CreateModel(
            name='ReportCardConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_comments', models.BooleanField(default=True, help_text='Include teacher comments on report cards', verbose_name='Include Teacher Comments')),
                ('include_attendance', models.BooleanField(default=True, help_text='Include attendance records on report cards', verbose_name='Include Attendance')),
                ('include_conduct', models.BooleanField(default=True, help_text='Include conduct/behavior assessment on report cards', verbose_name='Include Conduct')),
                ('include_extracurricular', models.BooleanField(default=False, help_text='Include extracurricular activities on report cards', verbose_name='Include Extracurricular')),
                ('principal_signature_required', models.BooleanField(default=True, help_text="Require principal's signature on report cards", verbose_name='Principal Signature Required')),
                ('class_teacher_signature_required', models.BooleanField(default=True, help_text="Require class teacher's signature on report cards", verbose_name='Class Teacher Signature Required')),
                ('include_next_term_begins_date', models.BooleanField(default=True, help_text='Include next term begins date on report cards', verbose_name='Include Next Term Date')),
                ('include_house_master_comment', models.BooleanField(default=False, help_text="Include house master's comment (for boarding schools)", verbose_name='Include House Master Comment')),
                ('include_counselor_comment', models.BooleanField(default=False, help_text="Include guidance counselor's comment", verbose_name='Include Counselor Comment')),
                ('show_grade_descriptions', models.BooleanField(default=True, help_text='Show grade descriptions on report cards', verbose_name='Show Grade Descriptions')),
                ('show_score_breakdown', models.BooleanField(default=True, help_text='Show breakdown of scores (classwork, homework, test, exam)', verbose_name='Show Score Breakdown')),
                ('show_class_position', models.BooleanField(default=True, help_text="Show student's position in class", verbose_name='Show Class Position')),
                ('show_overall_position', models.BooleanField(default=True, help_text="Show student's overall position in school", verbose_name='Show Overall Position')),
                ('show_grade_color_coding', models.BooleanField(default=True, help_text='Use color coding for grades on report cards', verbose_name='Use Color Coding')),
                ('school_logo', models.ImageField(blank=True, help_text='Logo to display on report cards', null=True, upload_to='school_logos/', verbose_name='School Logo')),
                ('header_color', models.CharField(default='#2E7D32', help_text='Color for report card header (hex code)', max_length=7, verbose_name='Header Color')),
                ('footer_text', models.TextField(blank=True, help_text='Text to display in report card footer', verbose_name='Footer Text')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A4', max_length=20, verbose_name='Paper Size')),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=10, verbose_name='Orientation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_config', to='core.schoolconfiguration')),
            ],
            options={
                'verbose_name': 'Report Card Configuration',
                'verbose_name_plural': 'Report Card Configuration',
            },
        ),
        migrations.CreateModel(
            name='PromotionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_pass_mark', models.DecimalField(decimal_places=2, default=40.0, help_text='Minimum percentage to pass in primary school', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Primary Pass Mark (%)')),
                ('primary_must_pass_english', models.BooleanField(default=True, help_text='Students must pass English to be promoted', verbose_name='Must Pass English (Primary)')),
                ('primary_must_pass_maths', models.BooleanField(default=True, help_text='Students must pass Mathematics to be promoted', verbose_name='Must Pass Mathematics (Primary)')),
                ('primary_max_failed_subjects', models.IntegerField(default=2, help_text='Maximum number of failed subjects allowed for promotion in primary', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Failed Subjects (Primary)')),
                ('jhs_pass_mark', models.DecimalField(decimal_places=2, default=45.0, help_text='Minimum percentage to pass in JHS', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='JHS Pass Mark (%)')),
                ('jhs_must_pass_core', models.BooleanField(default=True, help_text='Must pass all core subjects (English, Math, Science, Social)', verbose_name='Must Pass Core Subjects (JHS)')),
                ('jhs_max_failed_electives', models.IntegerField(default=1, help_text='Maximum failed elective subjects allowed in JHS', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Failed Electives (JHS)')),
                ('automatic_promotion_to_p4', models.BooleanField(default=True, help_text='Automatic promotion from P1-P3 (common in Ghanaian schools)', verbose_name='Automatic Promotion to P4')),
                ('require_bnce_for_jhs3', models.BooleanField(default=True, help_text='Require Basic Education Certificate for JHS3 promotion', verbose_name='Require BNCE for JHS3')),
                ('offer_remedial_classes', models.BooleanField(default=True, help_text='Offer remedial classes for struggling students', verbose_name='Offer Remedial Classes')),
                ('remedial_pass_mark', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum percentage to pass remedial assessment', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remedial Pass Mark (%)')),
                ('max_remedial_attempts', models.IntegerField(default=2, help_text='Maximum number of remedial attempts allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Max Remedial Attempts')),
                ('allow_conditional_promotion', models.BooleanField(default=True, help_text='Allow conditional promotion with specific requirements', verbose_name='Allow Conditional Promotion')),
                ('conditional_promotion_min_attendance', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance percentage for conditional promotion', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Min Attendance for Conditional Promotion (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_config', to='core.schoolconfiguration')),
            ],
            options={
                'verbose_name': 'Promotion Configuration',
                'verbose_name_plural': 'Promotion Configuration',
            },
        ),
    ]
