# Generated by Django 4.2.26 on 2025-12-24 13:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_convert_to_percentage_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_subject_a211c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_class_a_245a37_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_ges_gra_8d3549_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_letter__ddb4b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_student_60c99b_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_total_s_bbb949_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_created_1a1fd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_class_a_e5a634_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_student_f03bed_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='core_grade_academi_f31478_idx',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='subjects_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of subjects graded'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classwork_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Classwork percentage score (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'Score cannot be negative'), django.core.validators.MaxValueValidator(Decimal('100.00'), 'Score cannot exceed 100%')], verbose_name='Classwork Score (%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exam percentage score (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'Score cannot be negative'), django.core.validators.MaxValueValidator(Decimal('100.00'), 'Score cannot exceed 100%')], verbose_name='Exam Score (%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='ges_grade',
            field=models.CharField(choices=[('1', '1 (90-100%) - Outstanding'), ('2', '2 (80-89%) - Excellent'), ('3', '3 (70-79%) - Very Good'), ('4', '4 (60-69%) - Good'), ('5', '5 (50-59%) - Satisfactory'), ('6', '6 (40-49%) - Fair'), ('7', '7 (30-39%) - Weak'), ('8', '8 (20-29%) - Very Weak'), ('9', '9 (0-19%) - Fail'), ('N/A', 'Not Available')], default='N/A', editable=False, help_text='Automatically determined GES grade', max_length=3, verbose_name='GES Grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='homework_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Homework percentage score (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'Score cannot be negative'), django.core.validators.MaxValueValidator(Decimal('100.00'), 'Score cannot exceed 100%')], verbose_name='Homework Score (%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (90-100%) - Outstanding'), ('A', 'A (80-89%) - Excellent'), ('B+', 'B+ (70-79%) - Very Good'), ('B', 'B (60-69%) - Good'), ('C+', 'C+ (50-59%) - Satisfactory'), ('C', 'C (40-49%) - Fair'), ('D+', 'D+ (30-39%) - Weak'), ('D', 'D (20-29%) - Very Weak'), ('F', 'F (0-19%) - Fail'), ('N/A', 'Not Available')], editable=False, help_text='Automatically determined letter grade', max_length=3, null=True, verbose_name='Letter Grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Test percentage score (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'Score cannot be negative'), django.core.validators.MaxValueValidator(Decimal('100.00'), 'Score cannot exceed 100%')], verbose_name='Test Score (%)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Automatically calculated weighted total score', max_digits=5, null=True, verbose_name='Total Score (%)'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject', 'academic_year', 'term'], name='core_grade_subject_85d4d1_idx'),
        ),
    ]
