# Generated by Django 4.2.11 on 2025-08-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_timeslot_timetable_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
    ]
