# Generated by Django 4.2.26 on 2025-12-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_grade_core_grade_subject_a211c3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentannouncement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this announcement is currently active'),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Parent-Teacher Meeting'), ('workshop', 'Workshop/Seminar'), ('celebration', 'Celebration/Performance'), ('sports', 'Sports Event'), ('academic', 'Academic Event'), ('other', 'Other')], default='meeting', max_length=50),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='bulk_id',
            field=models.CharField(blank=True, help_text='ID to group messages from same bulk send', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='parentannouncement',
            index=models.Index(fields=['target_type', 'is_active', '-created_at'], name='core_parent_target__523333_idx'),
        ),
        migrations.AddIndex(
            model_name='parentannouncement',
            index=models.Index(fields=['target_class', 'is_active'], name='core_parent_target__1e1319_idx'),
        ),
        migrations.AddIndex(
            model_name='parentannouncement',
            index=models.Index(fields=['created_at'], name='core_parent_created_d1fcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='parentevent',
            index=models.Index(fields=['start_date', 'end_date'], name='core_parent_start_d_15011d_idx'),
        ),
        migrations.AddIndex(
            model_name='parentevent',
            index=models.Index(fields=['is_whole_school', 'class_level'], name='core_parent_is_whol_ba160e_idx'),
        ),
        migrations.AddIndex(
            model_name='parentevent',
            index=models.Index(fields=['event_type', 'start_date'], name='core_parent_event_t_9b3be7_idx'),
        ),
        migrations.AddIndex(
            model_name='parentevent',
            index=models.Index(fields=['is_mandatory', 'start_date'], name='core_parent_is_mand_018476_idx'),
        ),
        migrations.AddIndex(
            model_name='parentguardian',
            index=models.Index(fields=['account_status', 'last_login_date'], name='core_parent_account_3d4268_idx'),
        ),
        migrations.AddIndex(
            model_name='parentguardian',
            index=models.Index(fields=['email'], name='core_parent_email_e4172f_idx'),
        ),
        migrations.AddIndex(
            model_name='parentguardian',
            index=models.Index(fields=['phone_number'], name='core_parent_phone_n_6439e4_idx'),
        ),
        migrations.AddIndex(
            model_name='parentguardian',
            index=models.Index(fields=['relationship'], name='core_parent_relatio_1cc7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='parentguardian',
            index=models.Index(fields=['created_at'], name='core_parent_created_8f85e6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentmessage',
            index=models.Index(fields=['receiver', 'is_read', '-timestamp'], name='core_parent_receive_ebc987_idx'),
        ),
        migrations.AddIndex(
            model_name='parentmessage',
            index=models.Index(fields=['sender', '-timestamp'], name='core_parent_sender__6c38f4_idx'),
        ),
        migrations.AddIndex(
            model_name='parentmessage',
            index=models.Index(fields=['parent', '-timestamp'], name='core_parent_parent__a31747_idx'),
        ),
        migrations.AddIndex(
            model_name='parentmessage',
            index=models.Index(fields=['is_bulk', 'bulk_id'], name='core_parent_is_bulk_2e6196_idx'),
        ),
        migrations.AddIndex(
            model_name='parentmessage',
            index=models.Index(fields=['priority', '-timestamp'], name='core_parent_priorit_aa27e8_idx'),
        ),
        migrations.AddIndex(
            model_name='parentmessage',
            index=models.Index(fields=['email_sent', 'sms_sent'], name='core_parent_email_s_c323c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='unique_phone_number'),
        ),
    ]
