# Generated by Django 4.2.26 on 2025-12-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_parentannouncement_is_active_parentevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string from the HTTP request', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Access'), ('BULK_MESSAGE_SENT', 'Bulk Message Sent'), ('OTHER', 'Other')], db_index=True, max_length=20),
        ),
    ]
