# Generated by Django 4.2.11 on 2025-09-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_timetable_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentguardian', to=settings.AUTH_USER_MODEL),
        ),
    ]
