# Generated by Django 4.2.11 on 2025-09-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_parentguardian_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentguardian',
            unique_together={('student', 'emergency_contact_priority')},
        ),
    ]
