# Generated by Django 4.2.26 on 2025-12-31 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_paymentgateway_pendingpayment_onlinepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bill_payments', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['is_confirmed'], name='core_billpa_is_conf_c359d6_idx'),
        ),
    ]
