# Generated by Django 4.2.26 on 2026-01-01 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_billpayment_confirmed_at_billpayment_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='academic_year',
            field=models.CharField(default='2026/2027', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', 'Academic year must be in format YYYY/YYYY')], verbose_name='Current Academic Year'),
        ),
    ]
