# Generated by Django 4.2.11 on 2025-09-07 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_alter_teacher_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='issued', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_bills', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Fee Categories'},
        ),
        migrations.AddField(
            model_name='feecategory',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('termly', 'Per Term'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semester', 'Per Semester'), ('annual', 'Annual'), ('custom', 'Custom')], default='termly', max_length=20),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bill')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.feecategory')),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='core.bill'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.bill'),
        ),
    ]
