# Generated by Django 4.2.26 on 2026-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_schoolconfiguration_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditalertrule',
            name='has_financial_access',
            field=models.BooleanField(default=True, verbose_name='Has Financial Access'),
        ),
    ]
