# Generated by Django 4.2.26 on 2026-01-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auditalertrule_has_financial_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_financial_access',
            field=models.BooleanField(default=False, help_text='Whether this user can access and manage financial operations', verbose_name='Has Financial Access'),
        ),
    ]
