# Generated by Django 5.2.6 on 2025-09-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_parentannouncement_parentevent_parentmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentguardian',
            options={'ordering': ['emergency_contact_priority', 'user__last_name'], 'verbose_name_plural': 'Parents/Guardians'},
        ),
        migrations.AlterUniqueTogether(
            name='parentguardian',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='core.student'),
        ),
        migrations.RemoveField(
            model_name='parentguardian',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='parentguardian',
            name='student',
        ),
    ]
