# Generated by Django 5.2.6 on 2025-09-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_parentguardian_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('on_time_submission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('graded_students', models.PositiveIntegerField(default=0)),
                ('pending_students', models.PositiveIntegerField(default=0)),
                ('late_submissions', models.PositiveIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment Analytics',
                'verbose_name_plural': 'Assignment Analytics',
                'ordering': ['-last_calculated'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'ordering': ['assignment__due_date', 'student'], 'verbose_name': 'Student Assignment', 'verbose_name_plural': 'Student Assignments'},
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='core.assignment'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['status'], name='core_studen_status_cbcdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['submitted_date'], name='core_studen_submitt_54a935_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['assignment', 'student'], name='core_studen_assignm_7a7fd6_idx'),
        ),
        migrations.AddField(
            model_name='assignmentanalytics',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.assignment'),
        ),
    ]
