# Generated by Django 5.2.6 on 2025-09-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_assignmentanalytics_alter_studentassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_attachments/'),
        ),
    ]
