# Generated by Django 5.2.6 on 2025-10-06 04:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_assignment_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("HOMEWORK", "Homework"),
                            ("CLASSWORK", "Classwork"),
                            ("TEST", "Test"),
                            ("EXAM", "Examination"),
                        ],
                        max_length=10,
                    ),
                ),
                ("max_score", models.PositiveSmallIntegerField(default=100)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("attachment", models.FileField(blank=True, null=True, upload_to="assignment_templates/")),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.subject")),
            ],
        ),
    ]
