# Generated by Django 4.2.26 on 2026-01-03 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_academic_term_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Maintenance Operations', help_text='Name for this maintenance record', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Maintenance',
                'verbose_name_plural': 'Data Maintenance',
                'ordering': ['-created_at'],
            },
        ),
        # migrations.RemoveField(
        #     model_name='pendingpayment',
        #     name='bill',
        # ),
        # migrations.RemoveField(
        #     model_name='pendingpayment',
        #     name='fee',
        # ),
        # migrations.RemoveField(
        #     model_name='pendingpayment',
        #     name='initiated_by',
        # ),
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['-academic_year', 'sequence_num'], 'verbose_name': 'Academic Period', 'verbose_name_plural': 'Academic Periods'},
        ),
        # Commented out RenameIndex operations
        # migrations.RenameIndex(...),
        # migrations.RenameIndex(...),
        # migrations.RenameIndex(...),
        # migrations.RenameIndex(...),
        # migrations.RenameIndex(...),
        # migrations.RenameIndex(...),
        
        # COMMENT THIS OUT - term column doesn't exist
        # migrations.RemoveField(
        #     model_name='academicterm',
        #     name='term',
        # ),
        
        migrations.AddField(
            model_name='timetable',
            name='academic_term',
            field=models.ForeignKey(blank=True, help_text='Link to academic period (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicterm', verbose_name='Academic Period'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='academic_year',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$')], verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark as active for current academic period', verbose_name='Active Period'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(blank=True, help_text="Optional custom name (e.g., 'First Term', 'Fall Semester')", max_length=100, verbose_name='Period Name'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='period_number',
            field=models.PositiveSmallIntegerField(help_text='1, 2, 3 for Terms; 1, 2 for Semesters; 1-4 for Quarters', verbose_name='Period Number'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        # migrations.DeleteModel(
        #     name='PendingPayment',
        # ),
    ]