# Generated by Django 5.2.6 on 2025-10-08 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_assignmenttemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="classwork_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)],
                verbose_name="Classwork (30%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="exam_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)],
                verbose_name="Exam (50%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="homework_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Homework (10%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="test_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Test (10%)",
            ),
        ),
    ]
