# Generated by Django 4.2.26 on 2026-01-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_create_datamaintenance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataMaintenance',
        ),
    ]
