# Generated by Django 4.2.26 on 2026-01-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_datamaintenance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academicterm',
            new_name='core_academ_period__b4d56e_idx',
            old_name='core_academ_period_sys_year_idx',
        ),
        migrations.RenameIndex(
            model_name='academicterm',
            new_name='core_academ_is_acti_b5a2e8_idx',
            old_name='core_academ_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='academicterm',
            new_name='core_academ_start_d_3ca7a0_idx',
            old_name='core_academ_start_end_date_idx',
        ),
        migrations.RenameIndex(
            model_name='fee',
            new_name='core_fee_academi_63a144_idx',
            old_name='core_fee_academic_term_idx',
        ),
        migrations.RenameIndex(
            model_name='grade',
            new_name='core_grade_academi_3f6ba4_idx',
            old_name='core_grade_academic_term_idx',
        ),
        migrations.RenameIndex(
            model_name='reportcard',
            new_name='core_report_academi_9f9e6e_idx',
            old_name='core_report_academic_term_idx',
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='term',
        ),
    ]
