# core/migrations/0031_feegenerationbatch_fee_generation_status_and_more.py
# Generated by Django 4.2.26 on 2026-01-04 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_rename_core_academ_period_sys_year_idx_core_academ_period__b4d56e_idx_and_more'),
    ]

    operations = [
        # 1. Create FeeGenerationBatch model FIRST
        migrations.CreateModel(
            name='FeeGenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),      
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('total_fees', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),        
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fee Generation Batch',
                'verbose_name_plural': 'Fee Generation Batches',
                'ordering': ['-generated_at'],
            },
        ),
        
        # 2. Add fields to FeeGenerationBatch (must be done before Fee references it)
        migrations.AddField(
            model_name='feegenerationbatch',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicterm'),
        ),
        migrations.AddField(
            model_name='feegenerationbatch',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feegenerationbatch',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_batches', to=settings.AUTH_USER_MODEL),     
        ),
        migrations.AddField(
            model_name='feegenerationbatch',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_batches', to=settings.AUTH_USER_MODEL),   
        ),
        
        # 3. Add generation_batch field to Fee FIRST (before creating index)
        migrations.AddField(
            model_name='fee',
            name='generation_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='core.feegenerationbatch', verbose_name='Generation Batch'),
        ),
        
        # 4. Add other fields to Fee
        migrations.AddField(
            model_name='fee',
            name='generation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('VERIFIED', 'Verified'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Status in the fee generation workflow', max_length=20, verbose_name='Generation Status'),
        ),
        migrations.AddField(
            model_name='fee',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locking Date'),
        ),
        migrations.AddField(
            model_name='fee',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_fees', to=settings.AUTH_USER_MODEL, verbose_name='Locked By'),
        ),
        migrations.AddField(
            model_name='fee',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Date'),
        ),
        migrations.AddField(
            model_name='fee',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fees', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        
        # 5. NOW create indexes (AFTER all fields exist)
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['generation_status'], name='core_fee_generat_799dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['generation_batch'], name='core_fee_generat_c90216_idx'),
        ),
    ]