# Generated by Django 5.2.6 on 2025-10-22 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_auditalertrule_auditreport_dataretentionpolicy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="content",
            new_name="message",
        ),
        migrations.AddField(
            model_name="announcement",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_class_levels",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated class levels (e.g., P1,P2,P3) or leave blank for all",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="UserAnnouncementView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dismissed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.announcement"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Announcement View",
                "verbose_name_plural": "User Announcement Views",
                "unique_together": {("user", "announcement")},
            },
        ),
    ]
