# Generated by Django 5.2.6 on 2025-10-24 14:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_rename_content_announcement_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicterm",
            options={
                "ordering": ["-academic_year", "term"],
                "verbose_name": "Academic Term",
                "verbose_name_plural": "Academic Terms",
            },
        ),
        migrations.AlterModelOptions(
            name="analyticscache",
            options={"verbose_name": "Analytics Cache", "verbose_name_plural": "Analytics Caches"},
        ),
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["-due_date", "subject"],
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="assignmenttemplate",
            options={"verbose_name": "Assignment Template", "verbose_name_plural": "Assignment Templates"},
        ),
        migrations.AlterModelOptions(
            name="attendanceanalytics",
            options={"verbose_name": "Attendance Analytics", "verbose_name_plural": "Attendance Analytics"},
        ),
        migrations.AlterModelOptions(
            name="attendanceperiod",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Attendance Period",
                "verbose_name_plural": "Attendance Periods",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancesummary",
            options={
                "ordering": ["student__last_name", "student__first_name"],
                "verbose_name_plural": "Attendance Summaries",
            },
        ),
        migrations.AlterModelOptions(
            name="auditalertrule",
            options={"verbose_name": "Audit Alert Rule", "verbose_name_plural": "Audit Alert Rules"},
        ),
        migrations.AlterModelOptions(
            name="auditreport",
            options={"verbose_name": "Audit Report", "verbose_name_plural": "Audit Reports"},
        ),
        migrations.AlterModelOptions(
            name="bill",
            options={"ordering": ["-issue_date"], "verbose_name": "Bill", "verbose_name_plural": "Bills"},
        ),
        migrations.AlterModelOptions(
            name="billitem",
            options={"verbose_name": "Bill Item", "verbose_name_plural": "Bill Items"},
        ),
        migrations.AlterModelOptions(
            name="classassignment",
            options={
                "ordering": ["class_level", "subject"],
                "verbose_name": "Class Assignment",
                "verbose_name_plural": "Class Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="dataretentionpolicy",
            options={"verbose_name": "Data Retention Policy", "verbose_name_plural": "Data Retention Policies"},
        ),
        migrations.AlterModelOptions(
            name="fee",
            options={"ordering": ["-date_recorded"], "verbose_name": "Fee", "verbose_name_plural": "Fees"},
        ),
        migrations.AlterModelOptions(
            name="feecategory",
            options={"ordering": ["name"], "verbose_name": "Fee Category", "verbose_name_plural": "Fee Categories"},
        ),
        migrations.AlterModelOptions(
            name="feediscount",
            options={"verbose_name": "Fee Discount", "verbose_name_plural": "Fee Discounts"},
        ),
        migrations.AlterModelOptions(
            name="feeinstallment",
            options={
                "ordering": ["due_date"],
                "verbose_name": "Fee Installment",
                "verbose_name_plural": "Fee Installments",
            },
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["academic_year", "term", "student__last_name"],
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
            },
        ),
        migrations.AlterModelOptions(
            name="gradeanalytics",
            options={"verbose_name": "Grade Analytics", "verbose_name_plural": "Grade Analytics"},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="parentannouncement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Parent Announcement",
                "verbose_name_plural": "Parent Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="parentevent",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Parent Event",
                "verbose_name_plural": "Parent Events",
            },
        ),
        migrations.AlterModelOptions(
            name="parentguardian",
            options={
                "ordering": ["emergency_contact_priority", "user__last_name"],
                "verbose_name": "Parent/Guardian",
                "verbose_name_plural": "Parents/Guardians",
            },
        ),
        migrations.AlterModelOptions(
            name="parentmessage",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Parent Message",
                "verbose_name_plural": "Parent Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="reportcard",
            options={
                "ordering": ["-academic_year", "-term"],
                "verbose_name": "Report Card",
                "verbose_name_plural": "Report Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["class_level", "last_name", "first_name"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"], "verbose_name": "Subject", "verbose_name_plural": "Subjects"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["user__last_name", "user__first_name"],
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"ordering": ["period_number"], "verbose_name": "Time Slot", "verbose_name_plural": "Time Slots"},
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={
                "ordering": ["class_level", "day_of_week"],
                "verbose_name": "Timetable",
                "verbose_name_plural": "Timetables",
            },
        ),
        migrations.AlterModelOptions(
            name="timetableentry",
            options={
                "ordering": ["time_slot__period_number"],
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
            },
        ),
        migrations.AddField(
            model_name="academicterm",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicterm",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="analyticscache",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assignmenttemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignmenttemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="attendanceanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="name",
            field=models.CharField(blank=True, help_text="Custom name for the period", max_length=100),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="days_other",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="days_sick",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="present_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="bill",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="billitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classassignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="feecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="feediscount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feeinstallment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feepayment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feepayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gradeanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentguardian",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentguardian",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="academic_year",
            field=models.CharField(default="2025/2026", max_length=9),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="current_term",
            field=models.PositiveSmallIntegerField(choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")], default=1),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="principal_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="school_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="school_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="school_name",
            field=models.CharField(default="Ghana Education Service School", max_length=200),
        ),
        migrations.AddField(
            model_name="schoolconfiguration",
            name="school_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="academicterm",
            name="academic_year",
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator("^\\d{4}/\\d{4}$")]),
        ),
        migrations.AlterField(
            model_name="attendanceperiod",
            name="is_locked",
            field=models.BooleanField(default=False, help_text="Lock period to prevent modifications"),
        ),
        migrations.AlterField(
            model_name="attendanceperiod",
            name="period_type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("custom", "Custom")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendanceperiod",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attendance_periods", to="core.academicterm"
            ),
        ),
        migrations.AlterField(
            model_name="classassignment",
            name="academic_year",
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator("^\\d{4}/\\d{4}$")]),
        ),
        migrations.AlterField(
            model_name="parentguardian",
            name="emergency_contact_priority",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="parentguardian",
            name="phone_number",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")]
            ),
        ),
        migrations.AlterField(
            model_name="parentguardian",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("F", "Father"),
                    ("M", "Mother"),
                    ("B", "Brother"),
                    ("S", "Sister"),
                    ("G", "Guardian"),
                    ("O", "Other Relative"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.CharField(default="Ghanaian", max_length=100),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes about attendance"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                    ("sick", "Sick"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="class_levels",
            field=models.CharField(help_text="Comma-separated list of class levels", max_length=50),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="date_of_joining",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="employee_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")]
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="qualification",
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(fields=["student", "date"], name="core_studen_student_7334b1_idx"),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(fields=["date", "status"], name="core_studen_date_d1c5d9_idx"),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(fields=["term", "student"], name="core_studen_term_id_b15a9e_idx"),
        ),
    ]
