# Generated by Django 5.2.6 on 2025-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_academicterm_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
