# Generated by Django 5.2.6 on 2025-10-25 21:15

from django.db import migrations, models
import django.core.validators
from django.core.validators import RegexValidator


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_teacher_employee_id"),
    ]

    operations = [
        # Alter teacher phone_number from varchar(20) to varchar(10)
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(
                max_length=10,
                validators=[
                    RegexValidator(
                        r'^0\d{9}$',
                        message="Phone number must be 10 digits starting with 0 (e.g., 0245478847)"
                    )
                ],
                help_text="10-digit phone number starting with 0 (e.g., 0245478847)"
            ),
        ),
        # Alter parentguardian phone_number from varchar(20) to varchar(10)
        migrations.AlterField(
            model_name='parentguardian',
            name='phone_number',
            field=models.CharField(
                max_length=10,
                validators=[
                    RegexValidator(
                        r'^0\d{9}$',
                        message="Phone number must be 10 digits starting with 0 (e.g., 0245478847)"
                    )
                ],
                help_text="10-digit phone number starting with 0 (e.g., 0245478847)"
            ),
        ),
        # Alter schoolconfiguration school_phone from varchar(20) to varchar(10)
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='school_phone',
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    RegexValidator(
                        r'^0\d{9}$',
                        message="Phone number must be 10 digits starting with 0 (e.g., 0245478847)"
                    )
                ],
                help_text="10-digit phone number starting with 0 (e.g., 0245478847)"
            ),
        ),
        # Alter subject code to be editable=False
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]