# Generated by Django 5.2.6 on 2025-10-26 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_update_phone_number_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="10-digit phone number starting with 0 (e.g., 0245478847)",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^0\\d{9}$", message="Phone number must be 10 digits starting with 0 (e.g., 0245478847)"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="employee_id",
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                help_text="10-digit Ghana number (e.g., 0245846641)",
                max_length=10,
                validators=[django.core.validators.RegexValidator("^0[235][0-9]{8}$")],
            ),
        ),
    ]
