# Generated by Django 5.2.6 on 2025-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_student_phone_number_alter_teacher_employee_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("is_school_holiday", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="teacher",
            name="employee_id",
            field=models.CharField(default="temporary", editable=False, max_length=20, unique=True),
        ),
    ]
