# Generated by Django 5.2.6 on 2025-10-29 20:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_holiday_alter_teacher_employee_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["academic_year", "term", "student__last_name", "subject__name"],
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Prevent further modifications to this grade", verbose_name="Is Locked"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="recorded_by",
            field=models.ForeignKey(
                help_text="User who recorded this grade",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recorded By",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="requires_review",
            field=models.BooleanField(
                default=False, help_text="Flag for administrative review", verbose_name="Requires Review"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="review_notes",
            field=models.TextField(
                blank=True, help_text="Notes from administrative review", verbose_name="Review Notes"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="academic_year",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}/\\d{4}$", "Academic year must be in format YYYY/YYYY"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="class_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="grades", to="core.classassignment"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="classwork_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Classwork assessment score (0-30%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"), "Score cannot be negative"),
                    django.core.validators.MaxValueValidator(Decimal("30.00"), "Classwork score cannot exceed 30.00%"),
                ],
                verbose_name="Classwork Score (30%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="exam_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final examination score (0-50%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"), "Score cannot be negative"),
                    django.core.validators.MaxValueValidator(Decimal("50.00"), "Exam score cannot exceed 50.00%"),
                ],
                verbose_name="Exam Score (50%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="ges_grade",
            field=models.CharField(
                choices=[
                    ("1", "1 (90-100%) - Outstanding - Excellent performance"),
                    ("2", "2 (80-89%) - Excellent - Strong performance"),
                    ("3", "3 (70-79%) - Very Good - Above average performance"),
                    ("4", "4 (60-69%) - Good - Meets expectations"),
                    ("5", "5 (50-59%) - Satisfactory - Needs improvement"),
                    ("6", "6 (40-49%) - Fair - Below expectations"),
                    ("7", "7 (30-39%) - Weak - Significant improvement needed"),
                    ("8", "8 (20-29%) - Very Weak - Concerning performance"),
                    ("9", "9 (0-19%) - Fail - Immediate intervention required"),
                    ("N/A", "Not Available"),
                ],
                default="N/A",
                editable=False,
                help_text="Automatically determined GES grade",
                max_length=3,
                verbose_name="GES Grade",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="homework_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Homework assignment score (0-10%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"), "Score cannot be negative"),
                    django.core.validators.MaxValueValidator(Decimal("10.00"), "Homework score cannot exceed 10.00%"),
                ],
                verbose_name="Homework Score (10%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional comments or notes about the grade", verbose_name="Teacher Remarks"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="grades", to="core.student"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="grades", to="core.subject"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="test_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Test/examination score (0-10%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"), "Score cannot be negative"),
                    django.core.validators.MaxValueValidator(Decimal("10.00"), "Test score cannot exceed 10.00%"),
                ],
                verbose_name="Test Score (10%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="total_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Automatically calculated total score",
                max_digits=5,
                null=True,
                verbose_name="Total Score",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["student", "academic_year", "term"], name="core_grade_student_ac1521_idx"),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["subject", "academic_year"], name="core_grade_subject_a211c3_idx"),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["class_assignment", "term"], name="core_grade_class_a_245a37_idx"),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["total_score"], name="core_grade_total_s_c75197_idx"),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["ges_grade"], name="core_grade_ges_gra_8d3549_idx"),
        ),
    ]
