# Generated by Django 5.2.6 on 2025-10-31 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_grade_options_grade_is_locked_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="letter_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+ (90-100%) - Outstanding - Excellent performance"),
                    ("A", "A (80-89%) - Excellent - Strong performance"),
                    ("B+", "B+ (70-79%) - Very Good - Above average performance"),
                    ("B", "B (60-69%) - Good - Meets expectations"),
                    ("C+", "C+ (50-59%) - Satisfactory - Needs improvement"),
                    ("C", "C (40-49%) - Fair - Below expectations"),
                    ("D+", "D+ (30-39%) - Weak - Significant improvement needed"),
                    ("D", "D (20-29%) - Very Weak - Concerning performance"),
                    ("F", "F (0-19%) - Fail - Immediate intervention required"),
                    ("N/A", "Not Available"),
                ],
                editable=False,
                help_text="Automatically determined letter grade",
                max_length=3,
                null=True,
                verbose_name="Letter Grade",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="grading_system",
            field=models.CharField(
                choices=[
                    ("GES", "Ghana Education System (1-9)"),
                    ("LETTER", "Letter Grading System (A-F)"),
                    ("BOTH", "Both Systems"),
                ],
                default="GES",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["letter_grade"], name="core_grade_letter__ddb4b4_idx"),
        ),
    ]
