# Generated by Django 5.2.6 on 2025-11-04 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_grade_letter_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="target_roles",
            field=models.CharField(
                choices=[
                    ("ALL", "All Users"),
                    ("STUDENTS", "Students"),
                    ("TEACHERS", "Teachers"),
                    ("ADMINS", "Administrators"),
                    ("CLASS", "Specific Classes"),
                ],
                default="ALL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billpayment",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "Mobile Money"),
                    ("check", "Check"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StudentCredit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("credit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(default="Overpayment", max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_fee",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.fee"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credits", to="core.student"
                    ),
                ),
                (
                    "used_for_fee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_credits",
                        to="core.fee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Credit",
                "verbose_name_plural": "Student Credits",
                "ordering": ["-created_date"],
            },
        ),
    ]
