# Generated by Django 5.2.6 on 2025-11-09 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_budget_expense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securityevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
            },
        ),
        migrations.RemoveIndex(
            model_name="securityevent",
            name="core_securi_timesta_b9db08_idx",
        ),
        migrations.RemoveIndex(
            model_name="securityevent",
            name="core_securi_event_t_167471_idx",
        ),
        migrations.RemoveIndex(
            model_name="securityevent",
            name="core_securi_severit_8ce51f_idx",
        ),
        migrations.RemoveIndex(
            model_name="securityevent",
            name="core_securi_user_id_eb6502_idx",
        ),
        migrations.RenameField(
            model_name="auditreport",
            old_name="report_file",
            new_name="file_path",
        ),
        migrations.RenameField(
            model_name="auditreport",
            old_name="is_downloaded",
            new_name="is_archived",
        ),
        migrations.RemoveField(
            model_name="dataretentionpolicy",
            name="applies_to",
        ),
        migrations.RemoveField(
            model_name="dataretentionpolicy",
            name="retention_days",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="auditalertrule",
            name="action",
            field=models.CharField(
                choices=[
                    ("ALERT", "Generate Alert"),
                    ("NOTIFY", "Send Notification"),
                    ("BLOCK", "Block Action"),
                    ("ESCALATE", "Escalate to Admin"),
                ],
                default="ALERT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditalertrule",
            name="condition_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="auditalertrule",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("FREQUENCY", "Frequency Threshold"),
                    ("PATTERN", "Pattern Detection"),
                    ("RISK_SCORE", "Risk Score Threshold"),
                    ("CUSTOM", "Custom Condition"),
                ],
                default="FREQUENCY",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditalertrule",
            name="created_by",
            field=models.ForeignKey(
                default=52,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_alert_rules",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditreport",
            name="generated_by",
            field=models.ForeignKey(
                default=52, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditreport",
            name="parameters",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dataretentionpolicy",
            name="retention_period_days",
            field=models.IntegerField(default=52, help_text="Number of days to retain data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataretentionpolicy",
            name="retention_type",
            field=models.CharField(
                choices=[
                    ("AUDIT_LOG", "Audit Logs"),
                    ("SECURITY_EVENT", "Security Events"),
                    ("USER_DATA", "User Data"),
                    ("BACKUP", "Backup Files"),
                ],
                default="AUDIT_LOG",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataretentionpolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="resolved_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_events",
                to="core.auditalertrule",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="title",
            field=models.CharField(default="AUDIT_LOG", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditalertrule",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditalertrule",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="auditalertrule",
            name="severity",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditreport",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="auditreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily Report"),
                    ("WEEKLY", "Weekly Report"),
                    ("MONTHLY", "Monthly Report"),
                    ("SECURITY", "Security Report"),
                    ("COMPLIANCE", "Compliance Report"),
                    ("CUSTOM", "Custom Report"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dataretentionpolicy",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dataretentionpolicy",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_ATTEMPT", "Login Attempt"),
                    ("DATA_ACCESS", "Data Access"),
                    ("DATA_MODIFICATION", "Data Modification"),
                    ("CONFIG_CHANGE", "Configuration Change"),
                    ("SECURITY_ALERT", "Security Alert"),
                    ("SYSTEM_EVENT", "System Event"),
                ],
                default="SYSTEM_EVENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="severity",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
