# Generated by Django 5.2.6 on 2025-11-13 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_securityevent_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billpayment",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="billpayment",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "Mobile Money"),
                    ("cheque", "Cheque"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["student", "academic_year", "term"], name="core_bill_student_b40258_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="core_bill_status_5e1525_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["due_date"], name="core_bill_due_dat_69b74b_idx"),
        ),
        migrations.AddIndex(
            model_name="billpayment",
            index=models.Index(fields=["bill", "payment_date"], name="core_billpa_bill_id_b6439f_idx"),
        ),
    ]
