# Generated by Django 5.2.6 on 2025-11-14 16:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_billpayment_reference_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={
                "ordering": ["academic_year", "category"],
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date"], "verbose_name": "Expense", "verbose_name_plural": "Expenses"},
        ),
        migrations.RemoveField(
            model_name="budget",
            name="amount",
        ),
        migrations.AddField(
            model_name="budget",
            name="actual_spent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="budget",
            name="allocated_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("SALARIES", "Salaries & Wages"),
                    ("UTILITIES", "Utilities"),
                    ("MAINTENANCE", "Maintenance & Repairs"),
                    ("SUPPLIES", "Teaching Supplies"),
                    ("EQUIPMENT", "Equipment & Furniture"),
                    ("TRANSPORT", "Transportation"),
                    ("PROFESSIONAL", "Professional Development"),
                    ("OTHER", "Other Expenses"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["date", "category"], name="core_expens_date_74c598_idx"),
        ),
    ]
