# Generated by Django 5.2.6 on 2025-11-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_budget_options_alter_expense_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.feecategory"),
        ),
    ]
