# Generated by Django 5.2.6 on 2025-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_budget_notes_alter_budget_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userannouncementview",
            options={
                "ordering": ["-viewed_at"],
                "verbose_name": "User Announcement View",
                "verbose_name_plural": "User Announcement Views",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("GRADE", "Grade Update"),
                    ("FEE", "Fee Payment"),
                    ("ASSIGNMENT", "Assignment"),
                    ("ATTENDANCE", "Attendance"),
                    ("GENERAL", "General"),
                    ("ANNOUNCEMENT", "Announcement"),
                    ("SYSTEM", "System"),
                    ("SECURITY", "Security"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
